### ISSUE TITLE
Development on the shell should not require Turso and should minimize dependence on it

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql-shell-go#100]
Currently test suites depend pretty heavily on the presence of a Turso database. Instead, the tests should be configured and run without anything related to Turso.  Ideally, all references to Turso are replaced with sqld, and instructions should be provided on running tests against a locally running sqld instance.

Additionally, the shell contains a number of Turso-specific implementation details that should be re-evaluated and replaced with libsql/sqld equivalents where possible.  For example:

- pkg/shell/shellerrors/errors.go
- internal/shell/history_test.go
- internal/db/utils.go
- internal/db/db.go

**Comment by haaawk** [comment]
Let's just move those tests to CI.
