### ISSUE TITLE
Should shell `.dump` use a transaction?

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql-shell-go#117]
sqlite3 `.dump` wraps the entire SQL output (after `PRAGMA foreign_keys=OFF;`) in `BEGIN TRANSACTION;` and `COMMIT;`. Turso's shell does not.  Should it?  That would defend against a partial set of statements from executing in the face of an error part way through.

**Comment by CodingDoug** [comment]
Oops, duplicate of #75

**Comment by luisfvieirasilva** [comment]
@CodingDoug, I'll close this one since #75 has a little bit more context about why we're missing transactions on .dump
