### ISSUE TITLE
 Parse semicolons correctly when creating triggers

### ISSUE THREAD

**Issue by douglasmdev** [libsql/libsql-shell-go#124]
Glauber has raised the following [issue](https://github.com/libsql/sqld/issues/464):

Given the following table:

``` sql
CREATE TABLE users (
        id text PRIMARY KEY DEFAULT (uuid4()) NOT NULL,
        updated_at integer DEFAULT CURRENT_TIMESTAMP NOT NULL
)
```
The following trigger statement works on sqlite3, but not on sqld:

```sql
CREATE TRIGGER update_updated_at AFTER UPDATE ON users FOR EACH ROW BEGIN UPDATE users SET updated_at = 0 WHERE id = NEW.id; end;
```

This is hapening because we treat semi-colons as the end of a statement, which is not true for `CREATE TRIGGER` statements.

**Comment by glommer** [comment]
just FYI, someone hit this again today. the workaround is to not use the shell for that for the time being, and use an SDK instead
